In [7]:
import pandas as pd

In [39]:
df=pd.read_csv('marketing_data.csv')

In [9]:
#check for shape of data set
df.shape

(12, 8)

In [40]:
df

,Campaign Id,Channel,Impressions,Clicks,Conversions,Cost,Revenue,Customers
0,C001,Facebook,10000.0,500.0,50.0,20000.0,75000.0,45.0
1,C002,Google Ads,8000.0,NaN,60.0,25000.0,90000.0,55.0
2,C003,Instagram,12000.0,600.0,NaN,18000.0,40000.0,28.0
3,C004,Email,5000.0,300.0,80.0,10000.0,120000.0,NaN
4,C005,LinkedIn,7000.0,200.0,20.0,NaN,30000.0,18.0
5,C006,YouTube,15000.0,700.0,40.0,30000.0,NaN,35.0
6,C007,Facebook,9000.0,450.0,55.0,22000.0,80000.0,50.0
7,C008,Google Ads,NaN,550.0,70.0,27000.0,110000.0,65.0
8,C009,Instagram,13000.0,650.0,35.0,20000.0,50000.0,30.0
9,C010,Email,6000.0,350.0,90.0,12000.0,140000.0,85.0
10,C011,Facebook,10000.0,500.0,50.0,20000.0,75000.0,45.0
11,C012,NaN,11000.0,500.0,60.0,26000.0,95000.0,60.0

In [8]:
df.columns

Index(['Campaign Id', 'Channel', 'Impressions', 'Clicks', 'Conversions',
       'Cost', 'Revenue', 'Customers'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Campaign Id  12 non-null     object
 1   Channel      11 non-null     object
 2   Impressions  11 non-null     float64
 3   Clicks       11 non-null     float64
 4   Conversions  11 non-null     float64
 5   Cost         11 non-null     float64
 6   Revenue      11 non-null     float64
 7   Customers    11 non-null     float64
dtypes: float64(6), object(2)
memory usage: 900.0+ bytes

In [11]:
df.describe()

,Impressions,Clicks,Conversions,Cost,Revenue,Customers
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,9636.363636,481.818182,55.454545,20909.090909,82272.727273,46.909091
std,3042.128441,150.453859,20.056738,6106.628292,33790.800254,19.112585
min,5000.000000,200.000000,20.000000,10000.000000,30000.000000,18.000000
25%,7500.000000,400.000000,45.000000,19000.000000,62500.000000,32.500000
50%,10000.000000,500.000000,55.000000,20000.000000,80000.000000,45.000000
75%,11500.000000,575.000000,65.000000,25500.000000,102500.000000,57.500000
max,15000.000000,700.000000,90.000000,30000.000000,140000.000000,85.000000

In [11]:
#check for existence of null values
df.isnull().sum()

Campaign Id    0
Channel        1
Impressions    1
Clicks         1
Conversions    1
Cost           1
Revenue        1
Customers      1
dtype: int64

In [42]:
#change column names to all lower case
df.columns=df.columns.str.lower()

In [13]:
df.duplicated(subset='campaign id')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [62]:
df.columns

Index(['campaign id', 'channel', 'impressions', 'clicks', 'conversions',
       'cost', 'revenue', 'customers'],
      dtype='object')

In [43]:
#replace space in column name with _
df.columns=df.columns.str.replace(' ','_')

In [44]:
df.columns

Index(['campaign_id', 'channel', 'impressions', 'clicks', 'conversions',
       'cost', 'revenue', 'customers'],
      dtype='object')

In [45]:
#replacing null values in click, conversion and impressions with MEAN values of respective column

fill_values={'impressions':df['impressions'].mean(),
             'clicks':df['clicks'].mean(),
            'conversions':df['conversions'].mean()}
#reassign fill_values to column 
df=df.fillna(value=fill_values)

In [46]:
#for handelling null in categorical value column i.e., channel, used MODE
#for handelling missing cose and revenue values, used MEDIAN
fill_values1={'channel':df['channel'].mode()[0],
            'cost':df['cost'].median(),
            'revenue':df['revenue'].median()}
#reassign fill_values to column 
df=df.fillna(value=fill_values1)

In [47]:
df

,campaign_id,channel,impressions,clicks,conversions,cost,revenue,customers
0,C001,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45.0
1,C002,Google Ads,8000.000000,481.818182,60.000000,25000.0,90000.0,55.0
2,C003,Instagram,12000.000000,600.000000,55.454545,18000.0,40000.0,28.0
3,C004,Email,5000.000000,300.000000,80.000000,10000.0,120000.0,NaN
4,C005,LinkedIn,7000.000000,200.000000,20.000000,20000.0,30000.0,18.0
5,C006,YouTube,15000.000000,700.000000,40.000000,30000.0,80000.0,35.0
6,C007,Facebook,9000.000000,450.000000,55.000000,22000.0,80000.0,50.0
7,C008,Google Ads,9636.363636,550.000000,70.000000,27000.0,110000.0,65.0
8,C009,Instagram,13000.000000,650.000000,35.000000,20000.0,50000.0,30.0
9,C010,Email,6000.000000,350.000000,90.000000,12000.0,140000.0,85.0
10,C011,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45.0
11,C012,Facebook,11000.000000,500.000000,60.000000,26000.0,95000.0,60.0

In [48]:
df['customers'].isnull().sum()

np.int64(1)

In [49]:
df['customers'] = df['customers'].fillna(df['conversions'])

In [50]:
df

,campaign_id,channel,impressions,clicks,conversions,cost,revenue,customers
0,C001,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45.0
1,C002,Google Ads,8000.000000,481.818182,60.000000,25000.0,90000.0,55.0
2,C003,Instagram,12000.000000,600.000000,55.454545,18000.0,40000.0,28.0
3,C004,Email,5000.000000,300.000000,80.000000,10000.0,120000.0,80.0
4,C005,LinkedIn,7000.000000,200.000000,20.000000,20000.0,30000.0,18.0
5,C006,YouTube,15000.000000,700.000000,40.000000,30000.0,80000.0,35.0
6,C007,Facebook,9000.000000,450.000000,55.000000,22000.0,80000.0,50.0
7,C008,Google Ads,9636.363636,550.000000,70.000000,27000.0,110000.0,65.0
8,C009,Instagram,13000.000000,650.000000,35.000000,20000.0,50000.0,30.0
9,C010,Email,6000.000000,350.000000,90.000000,12000.0,140000.0,85.0
10,C011,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45.0
11,C012,Facebook,11000.000000,500.000000,60.000000,26000.0,95000.0,60.0

In [51]:
df['customers']=df['customers'].astype(int)

In [22]:
df

,campaign_id,channel,impressions,clicks,conversions,cost,revenue,customers
0,C001,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45
1,C002,Google Ads,8000.000000,481.818182,60.000000,25000.0,90000.0,55
2,C003,Instagram,12000.000000,600.000000,55.454545,18000.0,40000.0,28
3,C004,Email,5000.000000,300.000000,80.000000,10000.0,120000.0,80
4,C005,LinkedIn,7000.000000,200.000000,20.000000,20000.0,30000.0,18
5,C006,YouTube,15000.000000,700.000000,40.000000,30000.0,80000.0,35
6,C007,Facebook,9000.000000,450.000000,55.000000,22000.0,80000.0,50
7,C008,Google Ads,9636.363636,550.000000,70.000000,27000.0,110000.0,65
8,C009,Instagram,13000.000000,650.000000,35.000000,20000.0,50000.0,30
9,C010,Email,6000.000000,350.000000,90.000000,12000.0,140000.0,85
10,C011,Facebook,10000.000000,500.000000,50.000000,20000.0,75000.0,45
11,C012,Facebook,11000.000000,500.000000,60.000000,26000.0,95000.0,60

In [52]:
df[['impressions','clicks','conversions']]=df[['impressions','clicks','conversions']].astype(int)

In [53]:
df

,campaign_id,channel,impressions,clicks,conversions,cost,revenue,customers
0,C001,Facebook,10000,500,50,20000.0,75000.0,45
1,C002,Google Ads,8000,481,60,25000.0,90000.0,55
2,C003,Instagram,12000,600,55,18000.0,40000.0,28
3,C004,Email,5000,300,80,10000.0,120000.0,80
4,C005,LinkedIn,7000,200,20,20000.0,30000.0,18
5,C006,YouTube,15000,700,40,30000.0,80000.0,35
6,C007,Facebook,9000,450,55,22000.0,80000.0,50
7,C008,Google Ads,9636,550,70,27000.0,110000.0,65
8,C009,Instagram,13000,650,35,20000.0,50000.0,30
9,C010,Email,6000,350,90,12000.0,140000.0,85
10,C011,Facebook,10000,500,50,20000.0,75000.0,45
11,C012,Facebook,11000,500,60,26000.0,95000.0,60

In [54]:
#Feature engineering
#to add Click through rate(CTR), it measures engagement
df['ctr']=df['clicks']/df['impressions']

#conversion rate, meassures effectiveness after clicks
df['conversion_rate']=df['conversions']/df['clicks']

#Cost per customer(CPC), how much to pay per click
df['cac']=df['cost']/df['customers']

#Profit
df['profit']=df['revenue']-df['cost']

In [55]:
df

,campaign_id,channel,impressions,clicks,conversions,cost,revenue,customers,ctr,conversion_rate,cac,profit
0,C001,Facebook,10000,500,50,20000.0,75000.0,45,0.050000,0.100000,444.444444,55000.0
1,C002,Google Ads,8000,481,60,25000.0,90000.0,55,0.060125,0.124740,454.545455,65000.0
2,C003,Instagram,12000,600,55,18000.0,40000.0,28,0.050000,0.091667,642.857143,22000.0
3,C004,Email,5000,300,80,10000.0,120000.0,80,0.060000,0.266667,125.000000,110000.0
4,C005,LinkedIn,7000,200,20,20000.0,30000.0,18,0.028571,0.100000,1111.111111,10000.0
5,C006,YouTube,15000,700,40,30000.0,80000.0,35,0.046667,0.057143,857.142857,50000.0
6,C007,Facebook,9000,450,55,22000.0,80000.0,50,0.050000,0.122222,440.000000,58000.0
7,C008,Google Ads,9636,550,70,27000.0,110000.0,65,0.057078,0.127273,415.384615,83000.0
8,C009,Instagram,13000,650,35,20000.0,50000.0,30,0.050000,0.053846,666.666667,30000.0
9,C010,Email,6000,350,90,12000.0,140000.0,85,0.058333,0.257143,141.176471,128000.0
10,C011,Facebook,10000,500,50,20000.0,75000.0,45,0.050000,0.100000,444.444444,55000.0
11,C012,Facebook,11000,500,60,26000.0,95000.0,60,0.045455,0.120000,433.333333,69000.0

In [57]:
df[['ctr','conversion_rate','cac','profit']].dtypes

ctr                float64
conversion_rate    float64
cac                float64
profit             float64
dtype: object

In [59]:
df[['ctr','conversion_rate','cac','profit']]=df[['ctr','conversion_rate','cac','profit']].round(2)

In [64]:
df.dtypes

campaign_id         object
channel             object
impressions          int64
clicks               int64
conversions          int64
cost               float64
revenue            float64
customers            int64
ctr                float64
conversion_rate    float64
cac                float64
profit             float64
dtype: object

In [61]:
#load this data set into postgre sql
from sqlalchemy import create_engine

In [62]:
username='postgres'
password='1234'
host='localhost'
port='5432'
database='Market'

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [63]:
#Load data frame to postgresql

table_name='market'
df.to_sql(table_name,engine,if_exists='replace',index=False)
print("Data loaded successfully")

Data loaded successfully